runtime: python27
runtime_config:
    python_version: 3.5
api_version: 1
threadsafe: false

entrypoint: gunicorn deepchat:app --log-file -

resources:
    memory_gb: 2.2

handlers:
- url: .*
  script: run.py

skip_files:
    - deepchat/static/assets/frozen_models/cornell/frozen_model.pb
    - .git

