model: DynamicBot
model_params:
  batch_size: 256
  decode: False
  dropout: 0.2
  embed_size: 64
  state_size: 512
  l1_reg: 0.0
  num_layers: 2
  learning_rate: 0.002
  optimizer: Adam
  reset_model: True
dataset: Cornell
dataset_params:
  data_dir: /home/brandon/terabyte/Datasets/cornell
  max_seq_len: 10
  vocab_size: 23765
