model: DynamicBot
dataset: Cornell
model_params:
  batch_size: 256
  ckpt_dir: out/cornell/basic_conf
  decode: False
  dropout: 0.2
  embed_size: 64
  encoder.class: chatbot.components.encoders.BasicEncoder
  decoder.class: chatbot.components.decoders.SimpleDecoder
  state_size: 512
  l1_reg: 0.0
  num_layers: 3
  learning_rate: 0.002
  optimizer: Adam
  reset_model: True
  steps_per_ckpt: 50
dataset_params:
  data_dir: /home/brandon/terabyte/Datasets/cornell
  max_seq_len: 10
  vocab_size: 40000
