dataset: data.Cornell
dataset_params:
  config_path: configs/example_cornell.yml
  data_dir: /home/brandon/Datasets/cornell
  data_name: cornell
  max_seq_len: 10
  optimize_params: true
  vocab_size: 10000
model: DynamicBot
model_params:
  base_cell: GRUCell
  batch_size: 256
  ckpt_dir: out/cornell/deep
  decode: false
  decoder.class: chatbot.components.decoders.BasicDecoder
  dropout_prob: 0.2
  embed_size: 128
  encoder.class: chatbot.components.encoders.BasicEncoder
  is_chatting: false
  l1_reg: 1.0e-06
  learning_rate: 0.002
  lr_decay: 0.98
  max_gradient: 5.0
  max_steps: 1000000
  num_layers: 3
  num_samples: 512
  optimizer: Adam
  reset_model: true
  sampled_loss: false
  state_size: 512
  steps_per_ckpt: 5
  temperature: 0.0
