# Example of good parameters for the cornell dataset.
# Note that most "good" parameters here are good for all the datasets,
# and so most of these are actually the default values.
# This file is just meant to illustrate what the user can change.
model: chatbot.DynamicBot
dataset: data.Cornell
model_params:
  base_cell: GRUCell
  ckpt_dir: out/cornell/basic
  decode: False
  batch_size: 256
  decoder.class: BasicDecoder
  encoder.class: BasicEncoder
  embed_size: 128
  learning_rate: 0.002
  num_layers: 1
  reset_model: True
  state_size: 512
  steps_per_ckpt: 250
dataset_params:
  data_dir: /home/brandon/Datasets/cornell
  vocab_size: 40000
  max_seq_len: 10
