# Simple, but (unusually) effective.
model: chatbot.DynamicBot
dataset: data.Cornell
model_params:
  base_cell: GRUCell
  ckpt_dir: out/cornell/small
  decode: False
  batch_size: 256
  decoder.class: BasicDecoder
  encoder.class: BasicEncoder
  embed_size: 64
  learning_rate: 0.002
  num_layers: 1
  reset_model: True
  state_size: 512
  steps_per_ckpt: 250
dataset_params:
  data_dir: /home/brandon/Datasets/cornell
  vocab_size: 30000
  max_seq_len: 10
