model: chatbot.DynamicBot
dataset: data.Reddit
model_params:
  encoder.class: chatbot.components.encoders.BasicEncoder
  decoder.class: chatbot.components.decoders.BasicDecoder
  batch_size: 256
  ckpt_dir: pretrained/reddit
  decode: True
  dropout: 0.0
  embed_size: 64
  state_size: 512
  l1_reg: 0.0
  num_layers: 2
  learning_rate: 0.002
  optimizer: Adam
  reset_model: False
dataset_params:
  data_dir: /home/brandon/terabyte/Datasets/reddit
  max_seq_len: 10
  vocab_size: 40000
