model: chatbot.DynamicBot
dataset: data.Reddit
model_params:
  base_cell: GRUCell
  ckpt_dir: out/reddit/example_reddit
  batch_size: 256
  embed_size: 64
  num_layers: 3
  reset_model: True
  steps_per_ckpt: 100
dataset_params:
  data_dir: /home/brandon/Datasets/reddit
  vocab_size: 23765
  max_seq_len: 10
