model: chatbot.DynamicBot
dataset: data.Reddit
model_params:
  ckpt_dir: out/reddit
  encoder.class: chatbot.components.encoders.BasicEncoder
  decoder.class: chatbot.components.decoders.BasicDecoder
  decode: False
  reset_model: True
dataset_params:
  data_dir: /home/brandon/terabyte/Datasets/reddit
  vocab_size: 23765