model: chatbot.DynamicBot
dataset: data.Cornell
model_params:
  batch_size: 32
  ckpt_dir: out/cornell/small_model
  decode: True
  dropout: 0.2
  embed_size: 32
  encoder.class: chatbot.components.encoders.BasicEncoder
  decoder.class: chatbot.components.decoders.SimpleDecoder
  learning_rate: 1e-4
  num_layers: 1
  optimizer: Adam
  reset_model: False
  state_size: 256
  steps_per_ckpt: 50
dataset_params:
  data_dir: /home/brandon/terabyte/Datasets/cornell
  max_seq_len: 10
  vocab_size: 10000