# Simple, but (unusually) effective.
model: chatbot.DynamicBot
dataset: data.TestData
model_params:
  base_cell: GRUCell
  ckpt_dir: out/test_data
  decode: False
  batch_size: 64
  decoder.class: BasicDecoder
  encoder.class: BasicEncoder
  embed_size: 32
  learning_rate: 0.002
  num_layers: 1
  reset_model: True
  state_size: 128
  steps_per_ckpt: 25
dataset_params:
  data_dir: /home/brandon/Datasets/test_data
  vocab_size: 100
  max_seq_len: 15
