# Experimenting with best model params for heroku server.
model: DynamicBot
dataset: Reddit
model_params:
  base_cell: LSTMCell
  batch_size: 256
  ckpt_dir: out/reddit/website_config/LSTM_1Lay_128Emb
  dropout_prob: 0.2
  decoder.class: BasicDecoder
  encoder.class: BasicEncoder
  embed_size: 128
  num_layers: 1
  reset_model: True
  state_size: 512
  steps_per_ckpt: 500
dataset_params:
  data_dir: /home/brandon/Datasets/reddit    # The only truly 'mandatory' parameter.
  vocab_size: 40000
  max_seq_len: 10
