# Experimenting with best model params for heroku server.
model: chatbot.DynamicBot
dataset: data.Reddit
model_params:
  base_cell: LSTMCell
  batch_size: 128
  ckpt_dir: out/reddit/website_config
  dropout_prob: 0.2
  decoder.class: chatbot.components.decoders.BasicDecoder
  encoder.class: chatbot.components.encoders.BasicEncoder
  embed_size: 128
  num_layers: 2
  reset_model: True
  state_size: 512
  steps_per_ckpt: 500
  reset_model: False
  temperature: 0.0
dataset_params:
  data_dir: /home/brandon/Datasets/reddit    # The only truly 'mandatory' parameter.
  vocab_size: 40000
  max_seq_len: 10
